### ISSUE TITLE
[Question] Memory Usage

### ISSUE THREAD

**Issue by iamrecursion** [artisticat1/obsidian-tikzjax#7]
Do you have any idea of the memory usage by the TikZJax worker? I'm running into consistent soft crashing on mobile with the plugin enabled and I wondered if you had any idea. I have not yet narrowed the crash down to Obsidian TikZJax; it could be a combination of plugins. I just figured it was worth asking before I have a moment to debug.

**Comment by artisticat1** [comment]
I'm not certain, but looking at the 'memory' tab in chrome's devtools seems to show that the worker uses little more than 10 MB of memory.

**Comment by iamrecursion** [comment]
Very curious! I wonder if something is misbehaving; more debugging to come!

**Comment by iamrecursion** [comment]
Hm. Now I can no longer reproduce it. Very strange. I'll close this, and keep an eye on things with a view to reopen if I can repro it or specifically narrow it down to TikZJax.
