### ISSUE TITLE
The diagram doesn't show up

### ISSUE THREAD

**Issue by SqrtLeaves** [artisticat1/obsidian-tikzjax#72]
I tried to follow the instructions. I installed the plugin, and copy the example code into obsidian, but the diagram didn't show up in the preview (instead, the code shows up). Do I need to install other things?

<img width="1410" alt="image" src="https://github.com/user-attachments/assets/ac465262-f93d-4057-8907-570f97365394">

**Comment by tyzheng03** [comment]
I used your code in obsidian, but I can work correctly. Maybe you can check if your plugin is enabled.
<img width="278" alt="Screenshot 2024-08-09 at 5 16 17 pm" src="https://github.com/user-attachments/assets/e1b94363-e84c-4bf9-94d7-69e3cef7658b">
<img width="140" alt="Screenshot 2024-08-09 at 5 16 30 pm" src="https://github.com/user-attachments/assets/0d79a5a0-f0c8-459c-8440-478d901cc43b">

**Comment by SqrtLeaves** [comment]
thanks, my bad, I forgot to enable the plugin, and I tried again, it worked.
