### ISSUE TITLE
[BUG] Chemfig: \usetikzlibrary{decorations.pathmorphing} can't be used

### ISSUE THREAD

**Issue by tyzheng03** [artisticat1/obsidian-tikzjax#75]
The problem shows as follows:

```tikz
\usepackage{chemfig}
\usetikzlibrary{decorations.pathmorphing}
\begin{document}
\chemfig{A-[,3,,,decorate,decoration=snake]B}
\end{document}
```
This code don't work in obsidian, witch should show as follow:

<img width="679" alt="Screenshot 2024-08-24 at 9 30 13 am" src="https://github.com/user-attachments/assets/44512c69-bb85-4d59-b410-e3f356d86833">

**Comment by ALTONPHA** [comment]
This code don't work in obsidian
